# Generated by Django 5.2 on 2025-08-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionquestion',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('finance', 'Finance'), ('health', 'Health')], default='sports', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('romance', 'Romance'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery')], default='adventure', max_length=20),
        ),
        migrations.RemoveField(
            model_name='predictioncomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='likes',
        ),
        migrations.AddField(
            model_name='predictioncomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storypart',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictioncomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storypart',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
