# Generated by Django 5.2 on 2025-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionquestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
